baseURL = "/"
languageCode = "en-us"
title = "VISR"

enableGitInfo = true

[build]
  writeStats = true

[params]
  description = "Dashboard for modelcontextprotocol repository metrics"
  repo = "modelcontextprotocol/modelcontextprotocol"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
